VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.name = "microwave-rails-app-box"
    vb.memory = 2048
 
    # Allow the VM to display the desktop environment 
    vb.customize ["modifyvm", :id, "--graphicscontroller", "vboxvga"]
    
    # vb.customize ["modifyvm", :id, "--cpus", "2"]
    # vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
    # vb.customize ["modifyvm", :id, "--ioapic", "on"]
    # vb.customize ["modifyvm", :id, "--vram", "128"]
    # vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
  end

  config.vm.network "forwarded_port", guest: 3000, host: 4000
  config.vm.network "forwarded_port", guest: 9292, host: 5000
  config.vm.synced_folder "./", "/home/vagrant/microwave-workspace"

  config.berkshelf.berksfile_path = "../cookbook/Berksfile"
  config.berkshelf.enabled = true

  config.vm.provision "chef_solo" do |chef|
    chef.cookbooks_path = "../cookbook"
    chef.run_list = ['microwave-rails-chef']
  end

  config.vm.provision "shell" do |s|
    s.inline = "sudo apt-get update"
    s.inline = "sudo apt-get -y upgrade && sudo apt-get -y autoremove"
    s.inline = "sudo apt-get install -y ubuntu-desktop"
  end 
end
