---
driver:
  name: vagrant
  synced_folders:
    - ["../rails-app", "/home/vagrant/microwave-workspace"]
  network:
    - ["forwarded_port", {guest: 3000, host: 4001}]
    - ["forwarded_port", {guest: 9292, host: 5001}]

provisioner:
  name: chef_solo

platforms:
  - name: microwave-rails-kitchen-box
    driver:
      box: ubuntu/trusty64

suites:
  - name: microwave-rails-chef
    run_list: 
      - microwave-rails-chef
